name: Test Project
on: push
jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: action/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependenices
        run: npm ci
      - name: Run Test
        run: npm test
